---
abstract: 'The command-line data processor for web content'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Capture::Tiny: 0
  Exporter: 0
  Test::Mock::LWP: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-aki
provides:
  App::aki:
    file: lib/App/aki.pm
    version: 0.01
requires:
  Data::MessagePack: 0
  Data::Printer: 0
  Getopt::Long: 0
  HTTP::Request: 0
  JSON: 0
  JSON::Pointer: 0
  LWP::UserAgent: 0
  Pod::Usage: 0
  XML::TreePP: 0
  YAML::Syck: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/App-aki
version: 0.01
